config/application.rb
=> [App-49]: remove Application time zone

Gemfile, Gemfile.lock
=> [App-48]: remove Sprockets-Rails gem

Gemfile, Gemfile.lock
remove Rails gem, switch to separate Core Rails libraries
=> [App-20]: remove Rails gem, switch to separate Core Rails libraries

config/environments/development.rb, config/environments/production.rb
remove suppress from logger output for asset requests in Development / Production configs
=> [App-54]: remove suppress from logger output for asset requests in Development / Production configs

.gitignore
remove Public assets from gitignore
=> [App-57]: remove Public assets from gitignore

spec/rails_helper.rb
add Shoulda-Matchers config to RSpec config
=> [App-29]: add Shoulda-Matchers config to RSpec config

spec/rails_helper.rb
add FactoryBot config to RSpec config, include FactoryBot::Syntax::Methods
=> [App-44]: add FactoryBot config to RSpec config, include FactoryBot::Syntax::Methods

spec/rails_helper.rb
add Fail Fast option to RSpec config
=> [App-60]: add Fail Fast option to RSpec config

spec/rails_helper.rb, spec/spec_helper.rb
add Random Order option to RSpec config
=> [App-61]: add Random Order option to RSpec config

spec/rails_helper.rb, test/test_helper.rb
remove Fixtures config & context from both default and RSpec testing files
=> [App-63]: remove Fixtures config & context from both default and RSpec testing files

Gemfile, Gemfile.lock
remove and uninstall Redis gem
=> [App-65]: remove and uninstall Redis gem

Gemfile, Gemfile.lock
=> [App-39]: add Slack-Notifier gem

config/database.yml
add Test Postgres database password in database config
=> [App-68]: add Test Postgres database password in database config

.github/workflows/ci.yml
add Continuous-Integration workflow with GithubActions
=> [App-43]: add Continuous-Integration workflow with GithubActions

.github/workflows/ci.yml
add RSpec testing job step to GitHubActions CI workflow
=> [App-70]: add RSpec testing job step to GitHubActions CI workflow

.github/workflows/ci.yml
update GithubActions CI workflow to only trigger on push
=> [App-69]: update GithubActions CI workflow to only trigger on push

Gemfile, Gemfile.lock
add Brakeman gem - static analysis security vulnerability scanner
=> [App-72]: add Brakeman gem - static analysis security vulnerability scanner

.github/workflows/ci.yml
add static analysis vulnerability security scanning job to GithubActions CI workflow via Brakeman
=> [App-73]: add static analysis vulnerability security scanning job to GithubActions CI workflow via Brakeman

.github/workflows/ci.yml, Gemfile, Gemfile.lock, config/database.yml
Feature Branch: add initial Continuous-Integration jobs, set up with GithubActions
=> Feature Branch: add initial Continuous-Integration jobs, set up with GithubActions

app/views/layouts/application.html.erb
add Responsive Meta Tag to Application layout, do not shrink to fit
=> [App-75]: add Responsive Meta Tag to Application layout, do not shrink to fit

Gemfile, Gemfile.lock
=> [App-79]: add SimpleCov gem

test/application_system_test_case.rb
remove Rails default System testing files with Selenium & Chrome
=> [App-81]: remove Rails default System testing files with Selenium & Chrome

db/migrate/20220630224138_create_countries.rb
add Database migration for Country creation, add mandatory fields: name, iso_code
=> [App-85]: add Database migration for Country creation, add mandatory fields: name, iso_code

app/models/country.rb
=> [App-84]: add Country model

db/schema.rb
add Country to Database Schema via running the migration
=> [App-88/89]: add Country to Database Schema via running the migration

spec/factories/country.rb
add Country factory with defined name and iso_code
=> [App-86]: add Country factory with defined name and iso_code

.github/semantic.yml
set Semantic PRs to only validate the PR title / ignore commits title
=> [App-94]: set Semantic PRs to only validate the PR title / ignore commits title

.github/semantic.yml
add default list of Conventional Commit Types to Semantic PRs config
=> [App-95]: add default list of Conventional Commit Types to Semantic PRs config

.github/semantic.yml
add new type of feature_branch to Semantic PRs config list
=> [App-97]: add new type of feature_branch to Semantic PRs config list

Gemfile, Gemfile.lock
=> [App-105]: add License-Finder gem

spec/models/country_spec.rb
add Country model database columns specs
=> [App-106]: add Country model database columns specs

.gitignore, config/credentials/production.yml.enc
add Production Multi Env Encrypted Secure Credentials
gitignore Production Multi Env Encrypted Secure Credentials key
=> [App-100]: add Production Multi Env Encrypted Secure Credentials

config/credentials/test.key, config/credentials/test.yml.enc
add Testing Multi Env Encrypted Secure Credentials
do not gitignore Testing Multi Env Encrypted Secure Credentials key
=> [App-115]: add Testing Multi Env Encrypted Secure Credentials

Gemfile, Gemfile.lock
add Bullet gem to Development to kill N+1 queries, unused eager loading and lacking counter cache
=> [App-118]: add Bullet gem to Development to kill N+1 queries, unused eager loading and lacking counter cache

config/environments/development.rb
install Bullet, add default config to Development Env config
=> [App-119]: install Bullet, add default config to Development Env config

README.md
add GitHub Actions CI status badge for Staging to README
=> [App-132]: add GitHub Actions CI status badge for Staging to README

.github/workflows/dependency_vulnerabilities.yml, .github/workflows/static_analysis_security_vulnerabilities.yml, .github/workflows/testing.yml
Split Github Action CI workflow into three: Testing, Dependency Vulnerabilities, Static Analysis Security Vulnerabilities
=> [App-133]: Split Github Action CI workflow into three: Testing, Dependency Vulnerabilities, Static Analysis Security Vulnerabilities

README.md
update README to show three Staging security badges for new workflows
=> [App-136]: update README to show three Staging security badges for new workflows

Gemfile, Gemfile.lock
remove comments / not used Gems (including Debug) from Gemfile
=> [App-143/145]: remove comments / not used Gems (including Debug) from Gemfile

app/models/country.rb, db/migrate/20220630224138_create_countries.rb, db/schema.rb, spec/factories/country.rb, spec/models/country_spec.rb
Feature Branch: add Country model, tests & factory
=> Feature Branch: add Country model, tests & factory

spec/models/country_spec.rb
fix: add Country model database columns specs
=> [App-106]: fix: add Country model database columns specs

app/models/tournament.rb, db/migrate/20220712211955_create_tournaments.rb, db/schema.rb, spec/factories/tournament.rb, spec/models/tournament_spec.rb
Feature: add Tournament model, tests & factory
=> Feature: add Tournament model, tests & factory

.github/workflows/dependency_vulnerabilities.yml, .github/workflows/static_analysis_security_vulnerabilities.yml, .github/workflows/testing.yml
remove bundler cache from GHA workflows, lock x86_64-linux
=> [App-148]: remove bundler cache from GHA workflows, lock x86_64-linux

Gemfile.lock, config/license_finder.yml
add License-Finder config, add checks on bundler, yarn and npm package managers, set decision file to dependency_decisions.yml
=> [App-149]: add License-Finder config, add checks on bundler, yarn and npm package managers, set decision file to dependency_decisions.yml

.github/workflows/allowed_dependency_licensing.yml
add Allowed Dependency Licensing job as GitHub Actions workflow, add allowed licences
=> [App-151]: add Allowed Dependency Licensing job as GitHub Actions workflow, add allowed licences

.github/CODEOWNERS
set up Robert @wittywolk as CODEOWNER for every file in Application repository
=> [App-159]: set up Robert @wittywolk as CODEOWNER for every file in Application repository

app/models/country.rb, app/models/tournament.rb, db/migrate/20220714234432_add_tournaments_to_country.rb, db/schema.rb, spec/models/country_spec.rb, spec/models/tournament_spec.rb
add relationship: Country has many Tournaments, Tournament belongs to Country, add default specs
=> [App-171]: add relationship: Country has many Tournaments, Tournament belongs to Country, add default specs

app/api/countries/entities/country.rb, spec/api/countries/entities/country_spec.rb
add Countries context in API, add Entities context, add Country entity & specs
=> [App-173/174]: add Countries context in API, add Entities context, add Country entity & specs

.github/workflows/allowed_dependency_licensing.yml, .github/workflows/dependency_vulnerabilities.yml, .github/workflows/static_analysis_security_vulnerabilities.yml, .github/workflows/testing.yml
Feature: update GHA workflows to run on ubuntu-latest instead of ubuntu-18.04
=> Feature: update GHA workflows to run on ubuntu-latest instead of ubuntu-18.04

app/models/application_record.rb, app/models/country.rb, app/models/season.rb, app/models/tournament.rb
remove ApplicationRecord, set Models to inherit from ActiveRecord::Base
=> [App-175]: remove ApplicationRecord, set Models to inherit from ActiveRecord::Base

app/api/countries/entities/country.rb, app/models/application_record.rb, app/models/country.rb, app/models/season.rb, app/models/tournament.rb, db/migrate/20220714234432_add_tournaments_to_country.rb, db/schema.rb, spec/api/countries/entities/country_spec.rb, spec/models/country_spec.rb, spec/models/tournament_spec.rb
add Country relationship with Tournaments, add Country Entity, contexts and specs, remove ApplicationRecord
=> Feature: add Country relationship with Tournaments, add Country Entity, contexts and specs, remove ApplicationRecord

spec/spec_configuration.rb
remove unnecessary comments from spec_configuration file
=> [App-182]: remove unnecessary comments from spec_configuration file

.github/workflows/allowed_dependency_licensing.yml, config/dependency_decisions.yml
add allowed licences: json, 2.6.2, ruby to both config and GitHub Actions Allowed Dependency Licensing job
=> [App-195]: add allowed licences: json, 2.6.2, ruby to both config and GitHub Actions Allowed Dependency Licensing job

Gemfile, Gemfile.lock
hard code version of all the added Gems
=> [App-36]: hard code version of all the added Gems

.github/workflows/dependency_vulnerabilities.yml
update Dependency Vulnerabilities GitHub Actions job to one liner
=> [App-201]: update Dependency Vulnerabilities GitHub Actions job to one liner

.github/workflows/testing.yml
add Testing Encrypted Master Key to GitHub Actions Testing job
=> [App-203]: add Testing Encrypted Master Key to GitHub Actions Testing job

app/controllers/application_controller.rb
=> [App-209]: remove ApplicationController

app/api/exceptions/object_non_exists_error.rb
add Object Non Exists Error to Exceptions context
=> [App-211]: add Object Non Exists Error to Exceptions context

app/controllers/api_controller.rb
add API Controller, define & rescue from validation error with status 422
=> [App-212/213]: add API Controller, define & rescue from validation error with status 422

app/api/seasons/entities/season.rb, spec/api/seasons/entities/season_spec.rb
add Seasons context to API, add Season entity & spec
=> [App-218]: add Seasons context to API, add Season entity & spec

app/api/seasons/commands/add.rb, app/api/seasons/commands/contracts/add_contract.rb, spec/api/seasons/commands/add_spec.rb, spec/api/seasons/commands/contracts/add_contract_spec.rb
add Season 'add' Command, 'add' Contract & specs
=> [App-219]: add Season 'add' Command, 'add' Contract & specs

app/controllers/seasons_controller.rb, config/routes.rb, spec/controllers/seasons_controller_spec.rb
add Seasons Controller, add route & endpoint and specs for 'add' action, add seasons namespace to router
=> [App-221]: add Seasons Controller, add route & endpoint and specs for 'add' action, add seasons namespace to router

app/javascript/application.js, app/javascript/controllers/application.js, app/javascript/controllers/index.js, config/importmap.rb
Feature: initial Stimulus.js setup
=> Feature: initial Stimulus.js setup

Procfile.dev, bin/dev
add Foreman, development binstub & Procfile.dev for rails server and dartsass:watch
=> Feature: add Foreman, development binstub & Procfile.dev for rails server and dartsass:watch

app/api/exceptions/non_existent_object_error.rb
rename Object Non Exists error to Non Existent Object error
=> [App-236]: rename Object Non Exists error to Non Existent Object error

.rubocop.yml
add TargetRubyVersion configuration to AllCops in RuboCop config
=> [App-237]: add TargetRubyVersion configuration to AllCops in RuboCop config

db/migrate/20220727151509_create_tournament_editions.rb, db/schema.rb
add Database migration for Tournament Editions table
=> [App-238]: add Database migration for Tournament Editions table

app/models/tournament_edition.rb
=> [App-239]: add Tournament Edition model

spec/models/tournament_edition_spec.rb
add Tournament Edition model database columns specs
=> [App-240]: add Tournament Edition model database columns specs

spec/factories/tournament.rb, spec/factories/tournament_edition.rb
add Tournament Edition factory
=> [App-241]: add Tournament Edition factory

app/models/season.rb, app/models/tournament.rb, app/models/tournament_edition.rb, db/migrate/20220727155430_add_tournament_editions_to_season_and_tournament.rb, db/schema.rb, spec/factories/tournament_edition.rb, spec/models/season_spec.rb, spec/models/tournament_edition_spec.rb, spec/models/tournament_spec.rb
add Tournament Edition relationship - belongs to Season and Tournament, add migration, specs, update factories
=> [App-242]: add Tournament Edition relationship - belongs to Season and Tournament, add migration, specs, update factories

app/models/season.rb, app/models/tournament.rb, app/models/tournament_edition.rb, db/migrate/20220727151509_create_tournament_editions.rb, db/migrate/20220727155430_add_tournament_editions_to_season_and_tournament.rb, db/schema.rb, spec/factories/tournament.rb, spec/factories/tournament_edition.rb, spec/models/season_spec.rb, spec/models/tournament_edition_spec.rb, spec/models/tournament_spec.rb
Feature: add Tournament Editions model, specs, factory and relationship to Season & Tournament
=> Feature: add Tournament Editions model, specs, factory and relationship to Season & Tournament

app/api/seasons/commands/contracts/create_contract.rb, app/api/seasons/commands/create.rb, app/controllers/seasons_controller.rb, spec/api/seasons/commands/contracts/create_contract_spec.rb, spec/api/seasons/commands/create_spec.rb
rename Season 'add' Command, 'add' Contract & specs to 'create' - follow REST conventons
=> [App-244]: rename Season 'add' Command, 'add' Contract & specs to 'create' - follow REST conventons

config/credentials/development.yml.enc
add Sentry DSN to Development Encrypted Secure Credentials
=> [App-260]: add Sentry DSN to Development Encrypted Secure Credentials

config/initializers/sentry.rb
add Sentry initializer, set up default breadcrumbs logging
=> [App-261]: add Sentry initializer, set up default breadcrumbs logging

config/initializers/sentry.rb
set-up Sentry enabled environments to Development & Production
=> [App-262]: set-up Sentry enabled environments to Development & Production

config/initializers/sentry.rb
set-up Sentry to send sensitive data - user cookies, user ip, request body
=> [App-263]: set-up Sentry to send sensitive data - user cookies, user ip, request body

config/environments/staging.rb
=> [App-110]: add Staging Environment

config/database.yml
add Staging database configuration
=> [App-265]: add Staging database configuration

spec/spec_configuration.rb
add abort rule when ENV is Staging in RSpec configuration file
=> [App-266]: add abort rule when ENV is Staging in RSpec configuration file

config/initializers/sentry.rb
add Staging to Sentry enabled environments config
=> [App-269]: add Staging to Sentry enabled environments config

Gemfile, Gemfile.lock
=> [App-270]: add Dry-Initializer gem

Gemfile, Gemfile.lock
=> [App-271]: add Dry-Types gem
